### ISSUE TITLE
documentation on use within a team

### ISSUE THREAD

**Issue by rpietro** [todotxt/todo.txt-cli#130]
I know this is not the place to post this question, but after multiple attempts Yahoo won't let me join the mailing list, no clue why. anyway, question is: is there any documentation or articles on how to use todo.txt within a team project?

thanks

**Comment by karbassi** [comment]
@rpietro @gr0undzer0 Could you provide an update on what you did for your team for future readers?

I'm closing this, but please respond anyway.
