### ISSUE TITLE
Start task with @context

### ISSUE THREAD

**Issue by bjorngi** [todotxt/todo.txt-cli#149]
According to the specifications of todo.txt format all context must be preceded with a space, but if you start a task with a context, does this rule apply to this? Or is `@work call This Dude about+theAwesomeProject` a valid task?

**Comment by kalafut** [comment]
I agree with @bjorngi that this part of the spec is unclear.  To have in the same document an a example of a valid task:  `@GroceryStore Eskimo pies`, and shortly thereafter: "A context is *preceded by a single space* and an @ sign", isn't clear.

While we're at it, here's another nitpick: Why have the "a single space" requirement? This seems to go against the overarching "completely unstructured" goal of the format. 

    My    @work task  

should be parsed as "@work" being a context, IMHO.

I think the spec for projects and contexts should be reworded to something like:
"The first character of a context is: `@`. This first character of a project is: `+`. Projects and contexts are preceded by whitespace, or appear at the start of the line."

**Comment by karbassi** [comment]
This issue was moved to todotxt/todotxt#3
