### ISSUE TITLE
Symlink to todo.cfg

### ISSUE THREAD

**Issue by mejpark** [todotxt/todo.txt-cli#157]
I installed the Todo.txt CLI with Homebrew:

```
$ brew install todo-txt
```

I then attempted to create an event:

```
$ todo.sh add "Test"
Fatal Error: Cannot read configuration file /Users/Mike/.todo/config
```

I can fix the above error by creating a symbolic link to todo.cfg:

```
$ sudo ln -s /usr/local/Cellar/todo-txt/2.10/todo.cfg /Users/Mike/.todo/config
```

But, I assume that the symlink will be broken when Brew updates todo-txt. Is this the case?

Is it possible to have `/Users/Mike/.todo/config` always point to `todo.cfg`, even after Brew has updated the program?

Thank you.

**Comment by jonafato** [comment]
A better solution here is probably to use one of the supported ways of specifying the config file location:
- Using the defaults of [`~/.todo.cfg`](https://github.com/ginatrapani/todo.txt-cli/blob/master/todo.sh#L651) and [`~/todo.cfg`](https://github.com/ginatrapani/todo.txt-cli/blob/master/todo.sh#L642)
- Passing the [`-d` CLI flag](https://github.com/ginatrapani/todo.txt-cli/wiki/Tips-and-Tricks) (possibly with an alias to make things easier)
- Setting the [`TODOTXT_CFG_FILE` environment variable](https://github.com/ginatrapani/todo.txt-cli/blob/master/todo.sh#L142) in your environment

**Comment by karbassi** [comment]
When you install the tool via brew, you will see.

```
To configure, copy the default config to your HOME and edit it:
    cp #{prefix}/todo.cfg ~/.todo.cfg
```

Note: `#{prefix}` is the brew cask install location.
