### ISSUE TITLE
Support for non-latin or language independent markup

### ISSUE THREAD

**Issue by damascene** [todotxt/todo.txt-cli#171]
Most markups in todo.txt files (priority `(A)(B)` and `Date t:, due:`) depends on Latin characters so a user of other alphabets like Arabic, Russian, Chinese would have to switch keyboard to write the markup. It would be much easier for a user to write todo.txt tasks in his language letters without having to use Latin characters.

My thought is that many symbols that are available on every keyboard could be used like `# & ^  +__()*&&{} []` and numbers could be used for priorities.

example for due: you can use:
```
Visit London {2015-12-22}
```
For completed tasks:
```
× Visit London
```
For priorities:
```
(1) Save my life
(2) Visit my mother
```

**Comment by Dr-Terrible** [comment]
:+1:

**Comment by mabkenar** [comment]
Very good idea.
Is the  '×' in '× Visit London' available in other keyboard layouts? It is not available in American (en-US) layout, but it is available in Persian (fa-IR) layout, on GNU/Linux.

**Comment by damascene** [comment]
well, I think there should be a discussion on those markups. if it's not in common keyboard layouts then something else should be chosen IMO.

**Comment by karbassi** [comment]
This issue was moved to todotxt/todotxt#4
