### ISSUE TITLE
[Request] Hamster Project Integration

### ISSUE THREAD

**Issue by waldyd** [todotxt/todo.txt-cli#177]
Hello,

I would be great to integrate todo.txt with the Project Hamster (https://github.com/projecthamster)

**Comment by Adrianzo** [comment]
And what's project hamster?

Check the addons list:

https://github.com/ginatrapani/todo.txt-cli/wiki/Todo.sh-Add-on-Directory

There might be already something similar.

PS. please take the time when writing something, try to explain the "what? when? why? how?...". Specially when making requests.
