### ISSUE TITLE
Windows - installed cli but doesn't work?

### ISSUE THREAD

**Issue by p2635** [todotxt/todo.txt-cli#179]
I insalled cygwin as a non admin at work (as we don't have admin rights), then extracted the cli contents to my /home directory. I also chmod +x but when I execute the script it keeps repeating this no matter what I do:

```
./todo.sh add "hello"
Usage: todo.sh [-fhpantvV] [-d todo_config] action [task_number] [task_description]
Try 'todo.sh -h' for more information.

./todo.sh
Usage: todo.sh [-fhpantvV] [-d todo_config] action [task_number] [task_description]
Try 'todo.sh -h' for more information.
```
Am I doing something wrong?

**Comment by bduplanty** [comment]
Is this still an issue?  This weekend I installed in cygwin (but was VERY slow) and installed under a Linux Bash shell in windows:
https://itsfoss.com/install-bash-on-windows/

Works great and no issues.

**Comment by p2635** [comment]
I no longer use todo.txt-cli, closing this issue. Thanks for getting back to me though @bduplanty
