### ISSUE TITLE
Allow path override

### ISSUE THREAD

**Issue by mhalano** [todotxt/todo.txt-cli#181]
Hey guys!

I installed the todo.txt package (todotxt-cli) available on Ubuntu repository. I know, that's not an official package, but it's a cool way to keep things updated and working smooth.

This package uses a global configuration file (/etc/todo-txt/config even I don't like so much this path).

The problem is: I would like if each user on my system could change the TODO_DIR path. Ok, that's only me on my computer, but I don't want to change unnecessarily  the config file. The idea is if I put the TODO_DIR (maybe change to TODOTXT_DIR to keep a standard?) variable on ~/.bashrc, ~/.zshrc or ~/.profile the script understand and do the magic. I know, I could create my own config file with TODO_DIR declared and set TODOTXT_GLOBAL_CFG_FILE to point to it. The idea is permit the most trivial flags and parameters to be set using TODOTXT_\* varibles instead of using a config file. There will be not always possible (like the ANSI colors which was declared on config file). May be even create a parameter to set the path? So easily you could create an alias and define where is yours {todo,done,report}.txt files

**Comment by afranke** [comment]
I'm not sure whether this fits in the same request or if this should be something different, but I'd like to have a todo.txt file at the root of my code git repositories and have the todo.txt-cli tool automatically use it when I'm in that directory (and maybe even in subdirectories).

So maybe todo.txt-cli could by default (if no config is set) use pwd and the recursively the parent?

**Comment by p2635** [comment]
I just installed it on Ubuntu through repos as well, but I have no idea how to use it. Can anyone take me through it?

**Comment by mhalano** [comment]
@afranke I think there is better default path instead pwd, like some hidden directory in the home.

@p2635 I think a comment in a issue isn't the better place to find help. You could try the mailing list (even it's dead), read the wiki or google it.

**Comment by karbassi** [comment]
@mhalano Tell me if I understand this correctly. You want to be able to set a global environment variable (`TODO_DIR`) and have the `todo.cfg` to use that if found, otherwise to use the `todo.cfg` version, correct?

**Comment by mhalano** [comment]
Kind like this. I want to add to my ~/.bashrc a global variable TODO_DIR to define where is my todo.txt, done.txt, etc files. Not always I can change the todo.cfg file. I'm using Ubuntu, so the config file stays on /etc which I can't change (yeah, I'm root, I can change, but I wouldn't like to do this). Got it?

**Comment by murlakatamenka** [comment]
@mhalano 

`todo.sh` respects `TODOTXT_CFG_FILE` environment variable, so you can just set it up in your `~/.bashrc`file.
```sh
export TODOTXT_CFG_FILE="~/.../todo.cfg"
```
From configuration file itself you can set paths to all the files as you like:
```sh
export TODO_DIR="~/.../todo"

export TODO_FILE="$TODO_DIR/todo.txt"
export DONE_FILE="$TODO_DIR/done.txt"
export REPORT_FILE="$TODO_DIR/report.txt"
```

In this case you won't even need an alias that can also solve your issue in one line if you add it to `~/.bashrc`
```sh
alias t="todo.sh -c -d ~/.../todo.cfg"
```

**Comment by chrysle** [comment]
@inkarkat I think this can also be closed since a `TODO_DIR` environment variable exists now.

**Comment by inkarkat** [comment]
Agreed; we have plenty of variables and alternative config locations that this shouldn't be an issue. I'd also say that the global config location under `/etc` is more of a template for users, and not something I would ever edit and use directly.
