### ISSUE TITLE
Append and prepend for other files

### ISSUE THREAD

**Issue by mhalano** [todotxt/todo.txt-cli#184]
Should be a way to append and prepend items in other files than todo.txt. The idea is use more task lists than just todo.txt and work easy with them.

**Comment by karbassi** [comment]
@mhalano Can you explain this a little bit more? What are you trying to achieve with using multiple files?

An example will help greatly.

**Comment by mhalano** [comment]
I installed on Ubuntu (could be Debian) the 'todotxt-cli' package. This package has the config file on /etc/todo-txt/config. I can't change this file being a regular user (because the permission), and even I change (using sudo), the changes will apply to all users on my computer.
This file sets a lot of global variables. One is particular interesting: $TODO_DIR. This directory defines where the files like todo.txt and done.txt go. I want to put my files under ~/Dropbox, but the only option is to put under ~/.todo-txt/. Let's see a quick demo:
$ export TODO_DIR="~/Dropbox" #set the variable
$ echo $TODO_DIR #check the variable
$ todo-txt add "test"
$ cat ~/.todo-txt/todo.txt
test
$
The idea here is define where is the files the user would use to store tasks. Got it?

**Comment by mhalano** [comment]
@karbassi any news about this?

**Comment by mhalano** [comment]
@karbassi 

The idea is create and manage other to-do list files than just  todo.txt. For instance, may be I want a separate list like someday.txt (for my GTD's "Someday/Maybe") or a masterplan.txt with my plan to conquer the world. Did you understand?

**Comment by karbassi** [comment]
@mhalano, the command you can use is `addto`. There is also `mv`.

```shell
$ todo.sh addto DEST "TEXT TO ADD"
```
> Adds a line of text to any file located in the todo.txt directory.
> For example, `addto inbox.txt "decide about vacation"`

**Comment by mhalano** [comment]
@karbassi Could have an alias? like "todo.sh inbox "text to add""? The idea is auto fulfill the extension, because, come on, always be text files.

**Comment by karbassi** [comment]
@mhalano 

Create a bash alias to the command and use that alias.

```shell
# In your bash config/bashrc
alias inbox='todo.sh addto inbox'

# Use this after reloading your bash session/config
inbox "text to add"
```

**Comment by mhalano** [comment]
@karbassi 

that's a poor solution. I think more people could have benefits if become able to split a big todo.txt on smaller lists, like inbox.txt, someday.txt, todo.txt, etc. It's just a dummy auto-complete. A nice feature and relatively easy to be implemented.
