### ISSUE TITLE
Edit option

### ISSUE THREAD

**Issue by mhalano** [todotxt/todo.txt-cli#185]
Should have an "edit|e" option to edit a task instead of just update option, because update option rewrite all line and may be you want just fix a typo or change a word.

**Comment by crvs** [comment]
I guess adding something like this to the  switch case would work... not sure though

> edit | e)
>     TEMP=$(tempfile)
>     itemString = getTodo $1
>     itemString > $TEMP
>     $EDITOR $TEMP && itemString = cat $TEMP
>    todo.sh update $1 $itemString # this should be replaced with some internal function I guess

**Comment by crvs** [comment]
also when your doing replace, hitting tab from an empty string inserts the current value of the given todo item i.e. if you have

```bash
01 look dumbfounded into empty space
02 pretend to be doing something important
03 pretend i did something important
04 look smart in front of cameras
05 buy camera to look smart in front of
```

and you do
```bash
$ todo.sh replace 01 <tab>
```
it gets completed to
```bash
$ todo.sh replace 01 'look dumbfounded into empty space'
```
and you can just edit that (and in case you have zsh with vi mode pressing `v` will drop you into a vim buffer with that line)

**Comment by karbassi** [comment]
@inkarkat @ginatrapani: Thoughts on adding `edit` as an option within the project? There is a plugin for it for some time now.

I'm on the fence on this myself. The cli's purpose is to allow CRUD actions without opening up the file. On the other hand, sometimes it's easy to open up the `todo.txt` in vim and edit/delete/or add in the comfort of vim.

**Comment by ginatrapani** [comment]
I'm also on the fence about this for the same reasons, and my guiding principle is: when I'm not sure, I default to no. We don't want to add code, complexity, and test coverage for features that we're not absolutely convinced are obviously core. The reason the CLI is pluggable is to enable stuff just like this. My two cents.

**Comment by karbassi** [comment]
@ginatrapani I agree. 

I'm closing this since the [edit](https://github.com/mbrubeck/todo.txt-cli/blob/master/todo.actions.d/edit) by @mbrubeck add-on handles this use case.

**Comment by inkarkat** [comment]
+1 for closing; the suggested implementation is simplistic; add-ons can do this, and in a more powerful way.

**Comment by kylemart** [comment]
> also when your doing replace, hitting tab from an empty string inserts the current value of the given todo item i.e. if you have
> 
> ```shell
> 01 look dumbfounded into empty space
> 02 pretend to be doing something important
> 03 pretend i did something important
> 04 look smart in front of cameras
> 05 buy camera to look smart in front of
> ```
> 
> and you do
> 
> ```shell
> $ todo.sh replace 01 <tab>
> ```
> 
> it gets completed to
> 
> ```shell
> $ todo.sh replace 01 'look dumbfounded into empty space'
> ```
> 
> and you can just edit that (and in case you have zsh with vi mode pressing `v` will drop you into a vim buffer with that line)

This was really helpful for me. Just what I wanted :)

For future readers who can't get this working:
Originally, this wasn't working for me. For some reason the completions script installed by the included Makefile wasn't getting picked up from `/usr/local/share/bash_completion.d`. I'm really not sure why; it should be getting picked up based on my research. For now, I simply added a `.bash_completion` file to my home directory and source the completion script like so:
```
# Added for todo.sh.
#
# Note: Not sure why, but for some reason this path is not getting sourced by default.
# Decided it would be easier to leave it as-is and simply source it from here. If it
# makes sense to move the todo completion file, I should probably move it in the
# future and remove this script.
for bcfile in /usr/local/share/bash_completion.d/* ; do
  . $bcfile
done
```

If it makes sense to install the completion script elsewhere, I'll look into doing that later :) For now I just need to GTD. Not sure if @inkarkat or others know why it isn't getting picked up by default for me. Using Ubuntu 20.04.6 LTS within WSL.
