### ISSUE TITLE
todo.txt syntax should include a "comment rule"

### ISSUE THREAD

**Issue by polvoazul** [todotxt/todo.txt-cli#190]
I thing we should be able to add lines to todo.txt that are not going to be parsed as a task. 
There are two main advantages to that:
1. This could be used to write comments, that could range from simple file section separators to editor (such as VIM) hints.
2. We could use these comments to store non-task data such as a list of projects, or saved filters, or anything else the imagination wants. It would be easy to extend the format by using this.

I suggest the following syntax:

Any line starting with `"# "` is a comment, and should not be treated as a task. It should not count towards task numbers and should be, by default, ignored by the clients.
Each comment can also have a tag, that must be written like this `# {tag}:`. This tag means that specific clients can take advantage of that comment to provide additional functionality. A suggestion of a tag would be `proj`, such that we could drop a line in our todo.txt:

```
# proj: +buyGuitar +researchNewMusic ...
```

and tools could keep this projects 'alive' even without any tasks assigned to them.

Something like:

```
# filter: arts="+music OR +art OR +buyGuitar"
```

could be used by a client to save a named filter. Possibilities are endless!

I suggest tags are kept very small to keep things uncluttered.
Clients that don't understand a tag must simply discard that line as a comment.

I think todo.txt format is great, but it lacks a little bit of flexibility and I think this extension would enable clients to implement features without breaking other clients!

What do you guys think?

**Comment by iansowinski** [comment]
Just wanted to start the same issue here. I really would love some tools for commenting. With syntax highliting it's even easier to use todo.txt in text editor, and having comment rule for sorting list inside of text editor would be a big benefit.

**Comment by karbassi** [comment]
This issue was moved to todotxt/todotxt#1

**Comment by clach04** [comment]
Also see https://github.com/todotxt/todo.txt-cli/issues/158 and plugin https://github.com/schiesbn/todotxt/blob/master/todo.actions.d/hide
