### ISSUE TITLE
folders / categories

### ISSUE THREAD

**Issue by iveksl2** [todotxt/todo.txt-cli#193]
was wondering if its possible to have another category which to put projects into:
i.e. Social, business, health, etc. ?

**Comment by jrock2004** [comment]
Unless I am not understanding the ask, could you not do this?

```
@Social Go meet my friends
```

**Comment by craigmaloney** [comment]
You could also use a project tag (+social, +business, +health, etc.)

**Comment by bram85** [comment]
You could use project names with a slash to group them:

+Business/Administration
+Business/SecretProject
+Health/Sports
+Health
