### ISSUE TITLE
[Homepage] add Clockwork Tomato to TODO.txt compatible apps.

### ISSUE THREAD

**Issue by timoc** [todotxt/todo.txt-cli#200]
[Clockwork Tomato](https://play.google.com/store/apps/details?id=net.phlam.android.clockworktomato&hl=en) the fantastic (IMHO) pomodoro tool for Android has been supporting todo.txt integration (with sync via dropbox) for a while now. 

It supports multiple profiles with separate todo.txt files, so I use it to work through my personal and family todo.txt files.

I didn't see it mentioned on the homepage so created an issue for it, for those who want their pomodoro's in todo.txt flavor.

Full disclosure: I suggested the feature to the developers way back when - which is my only relationship with them.

**Comment by karbassi** [comment]
This issue was moved to todotxt/todotxt.github.io#5
