### ISSUE TITLE
request: number-based priority

### ISSUE THREAD

**Issue by PDiracDelta** [todotxt/todo.txt-cli#205]
Priority is now Alphabet-based. This only leaves for 26 possible priority levels.
People with big projects might want to have more levels, and I can't see why that should be hard to implement.

Is it possible to change the priority indicator from a char to an int? This gives us a lot more flexibility, and basically for free (24 additional bits is nothing compared to the total line size).

Much appreciated!

**Comment by inkarkat** [comment]
I would love to hear more details or examples about your prioritization scheme. Based on my experience, a handful priorities is more than enough. The CLI client just provides different default highlightings for `A`-`C`. I sometime use additional priorities, like `P` for tasks in progress, or `Z` for very low-prio ones.

Most literature seems to corroborate this, e.g. Stephen Covey's quadrants (`I, II, III, IV`), GTD (which highly influenced todo.txt) [doesn't like pure prioritization at all](http://gettingthingsdone.com/newsletters/archive/0512.html).

In any case, there are now dozens of different todo.txt implementations out there. Though changing the format probably wouldn't amount to much (a regular expression here, a line of code there), making the switch consistently and in a timely way would be very hard. You'd need to bring up very good arguments (and a lot of vocal supporters) for this change to happen.

**Comment by PDiracDelta** [comment]
Valid remark, @inkarkat . I didn't think about all the dependencies.

My scheme would rather be time-sequence based than priority based. I like to think out which steps are necessary to complete a certain project, and list dependencies their dependencies and implied chronology (B comes after A if it is dependent on A). This chronology could be represented by the priority function in todo.txt, but currently allows for only 26 discrete, abstract moments in time.

Of course I could keep a separate list with chronologies, like I do now, but it would have been nice to know that there is software that integrates this functionality.

Thanks for your reply!

**Comment by awitherow** [comment]
@PDiracDelta have you considered using an addon for this?

https://github.com/ginatrapani/todo.txt-cli/wiki/Todo.sh-Add-on-Directory#outline--plan-with-an-outline-sync-your-next-actions

**Comment by inkarkat** [comment]
To me, that sounds like a clear misuse of priorities. `todo.sh lspri c` for example would then list all tasks that are dependent on two previous ones; that's not a useful report.

Unfortunately, there's little built-in support for such dependencies. I have built a rather sophisticated set of add-on actions for dependency handling as part of [my todo.sh extensions](https://github.com/inkarkat/todo.txt-cli-ex). [This test](https://github.com/inkarkat/todo.txt-cli-ex/blob/master/tests/t2090-dependency-workflow.sh) provides an overview of the involved actions. Its biggest downside is that the task references are the task numbers, so I also need to hook into the built-in archive action to adapt the references whenever tasks are removed.

**Comment by craigmaloney** [comment]
I've found that I use projects as links for dependencies. eg: If I'm learning the Scheme programming language then I have a project like:
```
Learn the +scheme language for my presentation +project
```
and then my tasks are:
```
Read through ch. 5 of Realm of Racket +scheme @read 
Play with the examples from ch. 5 of Realm of Racket +scheme @computer 
```
etc.

I agree though that using priorities for this sort of linking is going to make things weird.

**Comment by karbassi** [comment]
Since this has been discussed and no new updated in over a month, I'm closing the issue.

Go ahead and comment again if there are any updates.
