### ISSUE TITLE
config file option for always prepend date

### ISSUE THREAD

**Issue by plittlefield** [todotxt/todo.txt-cli#206]
Is there a config file option for this?

`-t Prepend the current date to a task automatically when it's added.`

Thanks.

**Comment by butterflyfree** [comment]
How with God is or isnt this?

**Comment by inkarkat** [comment]
From `todo.sh -v -v help`:

    TODOTXT_DATE_ON_ADD             is same as option -t (1)/-T (0)

Put this into your `~/.todo.cfg`, like this:

    # Prepend the date to any added task.
    export TODOTXT_DATE_ON_ADD=1

**Comment by plittlefield** [comment]
Thank you!
