### ISSUE TITLE
Is the project active?

### ISSUE THREAD

**Issue by karbassi** [todotxt/todo.txt-cli#207]
Hello @ginatrapani,

First of all, I fully understand that you are an extremely busy person, so please do not take this as a criticism. 

You've created an amazing toolset here that many people are using. However, it seems like there hasn't been any management of this project as of late.

There are many PRs that would benefit from a review and merge/reject. 

The question at hand is, **will you be coming back to the project, willing to add another maintainer, or allow a community fork to allows multiple people to work on it?**

Cheers! 💯

**Comment by karbassi** [comment]
Created @todotxt and [todotxt/todo.txt-cli](https://github.com/todotxt/todo.txt-cli).

If anyone wants to add some PRs there, we can vote and merge them.

Also, anyone who wants to be an active developer, PM me.

**Comment by zagortenay333** [comment]
There doesn't appear to be any discussion the the todo.txt format either. Surely it's not set in stone, and it might be improved/expanded/tweaked.

**Comment by inkarkat** [comment]
@karbassi Thank you for picking up this project! It'll probably be just a slow trickle of issues and PRs, but it's good that people see it's still maintained. I would be willing to comment on issues, and I also have some minor enhancements on my own todo list :-) I had been pretty active on this project some time ago, and now am mostly satisfied with the tool.

So, unless you intend to be the single BDFL, I'd like to get access to https://github.com/todotxt/todo.txt-cli in order to help out.

**Comment by zagortenay333** [comment]
IMO, the todo.txt format should have it's own repository and not be part of the wiki of some cli program.

**Comment by karbassi** [comment]
@inkarkat Yes. I'd love to add you. You've been very active in the project in the past and would love to have you on the community fork. I have no intention in being BDFL 🥇 .

@zagortenay333 Add an "issue" in the community fork of the project if you'd like to discuss new ideas for the `todo.txt` format.

**Comment by bram85** [comment]
I also wrote topydo three years ago, in order to implement features missing in the (awesome) original todo.txt CLI. It might serve your needs as well.

https://www.topydo.org
https://github.com/bram85/topydo

**Comment by karbassi** [comment]
@bram85 I use your tool from time to time. 

I'd love to bring the todotxt project under a community fork. Would you like to bring your project over and work together?

You project seems stable and working, though.

**Comment by evanp** [comment]
I'm trying to reach @ginatrapani on other channels. It'd be great to get her feedback.

**Comment by karbassi** [comment]
@evanp Yes, I fully agree. I pinged her on twitter already. Did want to bother her via email.

**Comment by evanp** [comment]
I've sent a couple of emails and asked some mutual friends to alert her.

**Comment by ginatrapani** [comment]
Hi all -- I'd be delighted to have other maintainers come onto the project, because obviously I have not kept up with it. Ideally it's not a fork. Instead, I'd like to make a todo.txt organization and transfer my repositories over to it. It appears someone has created this: https://github.com/todotxt 

Is that anyone here?

**Comment by ginatrapani** [comment]
Oops, reading back up I see that is @karbassi. Do you want to delete the fork, invite me to the org, and I will transfer my repos over?

**Comment by karbassi** [comment]
@ginatrapani, perfect! 

I'll rename them (since we've made some PR merges already) and add you to the team.

Excited to have your blessing on this.

**Comment by ginatrapani** [comment]
@karbassi thanks! I tried transferring the repo and got this error message "todotxt already has a repository in the ginatrapani/todo.txt-cli network and You don’t have the permission to create repositories on todotxt"

So it looks like I'll need permission to create a repository in the org, and that we may have to delete and recreate whatever new patches you've applied after the fact.

**Comment by ginatrapani** [comment]
@karbassi one other q: should I also transfer over the Android and iOS apps? I have also fell deeply behind maintaining those, and I'd be happy to also share keys to the play store/iOS store/Dropbox API key. This might be easier to discuss via PM -- let me know if you're interested in those.

**Comment by evanp** [comment]
I'd really love to see the mobile apps continue to be developed! I use the Android one every day.

**Comment by karbassi** [comment]
@ginatrapani I worked with Github support to fix the issue with the transfer. She said

> Hi Ali,
> 
> I've detached `todotxt/todo.txt-cli-fork` as requested, and @ginatrapani should be able to transfer the repository now.
> 
> Let us know if you need anything else!
> 
> Best,
> Melissa

You should be able to transfer the repos over. Go ahead and transfer the android and ios repos as well. If you want, transfer anything todotxt over and have it sit under the ORG.

I'd love to work with you to have the URL point to https://todotxt.github.io.

**Comment by ginatrapani** [comment]
@karbassi thanks so much! I now get the error "You don’t have the permission to create repositories on todotxt." Can you make me an owner of the org?

I'd also be happy to share domain/twitter handle/Tumblr creds as well and move the site over to github pages.

**Comment by karbassi** [comment]
@ginatrapani done!

I'd love to find a core team who consists of a person who can handle the social media side. Any suggestions of people?

The domain task can be done quickly though. Do you want to maintain the domain and just point it to the new CNAME?

**Comment by ginatrapani** [comment]
@karbassi transferred all the repositories!

> I'd love to find a core team who consists of a person who can handle the social media side. Any suggestions of people?

Well, if there's actual news to report, I could handle social, and amplify project announcements on my personal networks, too. Speaking of communications, I will write up a note about this move to the mailing list, and for the tumblr/twitter account this weekend.

Speaking of the mailing list, Yahoo Mail is pretty old and squeaky! Are you interested in moving to Google Groups or at least becoming a mod on the current email list?

> The domain task can be done quickly though. Do you want to maintain the domain and just point it to the new CNAME?

Sure, I can do that. Once the new site is up?

**Comment by karbassi** [comment]
> @karbassi transferred all the repositories!

@ginatrapani YAY! 🚀 

> I could handle social, and amplify project announcements on my personal networks, too.

I think that would be best! You have a large network and the community could use more devs via it.

> Speaking of communications, I will write up a note about this move to the mailing list, and for the tumblr/twitter account this weekend.

That would be amazing! I plan on moving the `gh-pages` branch into a GitHub org page soon. Moreover, I know of a few people who are interested in having a discussion about the todo.txt format, so I'll create a repo for that as well.

Did you want to shoot me an email/DM to discuss messaging before it goes out to the masses?

>Speaking of the mailing list, Yahoo Mail is pretty old and squeaky! Are you interested in moving to Google Groups or at least becoming a mod on the current email list?

I say let's move the Yahoo Mail/Group to either here or Google Groups. I think that since most of the people who use this tool are tech-savvy people (I may be wrong here), they would be okay with using GitHub issues.

> Sure, I can do that. Once the new site is up?

I'll set up the repo soon and ping you when it's up.

**Comment by ginatrapani** [comment]
@karbassi 

Re: social

> I think that would be best!

Sounds great.

> Did you want to shoot me an email/DM to discuss messaging before it goes out to the masses?

Sure. Off the top of my head, the rough message bullets are:

* Todo.txt isn't dead! But I (Gina) have been busy and I want to stop blocking progress
* Happily the community is stepping in!

Introducing:

* the new todotxt org on GitHub -- this is NOT a fork, it is a transfer. All the core repositories live there, and all links to the original repo's on my personal github account now redirect to the new org.
* @karbassi created this org to my delight and with my blessing, and I, @karbassi and Ingo are the initial members
* @karbassi also created a new Gitter.im room to discuss all things todo.txt in real-time, which is awesome, please join us

What's next:

* renewed attention to languishing pull requests
* hopefully an effort to begin a todotxt.com redesign
* a discussion about the future of the mailing list (not sure if we should include this yet, or break this into a separate discussion)

What we're asking from you now:

* check out the new repositories
* add your suggestions, contributions, and opinions to the issues or send a PR!
* join us the https://gitter.im/todotxt/

> I plan on moving the gh-pages branch into a GitHub org page soon. Moreover, I know of a few people who are interested in having a discussion about the todo.txt format, so I'll create a repo for that as well.

Saw both of those, sounds good. I've been discussing/debating/defending/explaining the spirit of the format for 11 years now, so I appreciate fresh legs & eyes!

> I say let's move the Yahoo Mail/Group to either here or Google Groups. I think that since most of the people who use this tool are tech-savvy people (I may be wrong here), they would be okay with using GitHub issues.

The mailing list is a burden to maintain -- over the years it got spam-bombed, so I turned on moderation which required manual approvals, Yahoo Groups kind of sucks (as does Google Groups, in my opinion) -- but I always kept it going b/c email is way more accessible to everyone than GitHub is. Todo.txt has a lot of very savvy users, but it also has a lot of users who don't have GitHub accounts, and moving all discussions to issues would exclude those users. Also, GitHub issues are great for tracking tickets, but they aren't great for having discussions and offering tech support and promoting other Todo.txt related community efforts, which all happen on the mailing list. Also, there are so many repositories, it would be difficult for users to figure out what repo's issue tracker to use.

Gitter will be great for discussion! But also not very accessible to new users.

My point is, if inclusivity and accessibility are values we want to uphold as a community, a mailing list or non-GitHub forum is important. But as always this is just my opinion and based in my experience over the years, but I am fine with being overruled!

**Comment by karbassi** [comment]
@ginatrapani all that sounds great. Let's figure out our forum and project email address, and I think we're set to send this off.

**Comment by ginatrapani** [comment]
Okay cool -- I got caught up in the domain config stuff so I didn't finish the actual message draft, but I hope to have it ready to send tomorrow afternoon. By then the DNS propagation should be complete and we can add the shift to .org to the announcement as well.

**Comment by ginatrapani** [comment]
@karbassi @inkarkat I drafted the message here:

https://docs.google.com/document/d/1jYdkAiNfG5HyKHvaSWGElEwyMuaKawGG3OG6eHPASCE/edit?usp=sharing

Suggestions welcome! Take a look and leave any comments. I plan to post this to the mailing list, on the blog, and then tweet a link to it. I'm also having Postlight folks take a look at it. Once I get everyone's :+1: I'll send out.

**Comment by karbassi** [comment]
@ginatrapani looks good. I've added some suggestions.

Have we decided anything about a forum and email address?

**Comment by ginatrapani** [comment]
Alright, announcement sent! 

> Have we decided anything about a forum and email address?

I'm not sure what the path forward should be. We definitely need a private email address for code of conduct & security vulnerability reports, but I don't know the best service to set this up on. Let's create a separate ticket for this, and once we decide, I will do any of the DNS work required for it.

As for the forum, also not sure about path forward. Maybe something to discuss either on-list or in Gitter? Let's break that out into a separate ticket as well.

In the meantime, closing this! Thanks @karbassi & @inkarkat & @evanp!
