### ISSUE TITLE
Keep the todo.txt format spec in a separate repo

### ISSUE THREAD

**Issue by karbassi** [todotxt/todo.txt-cli#213]
_From @zagortenay333 on August 16, 2017 8:7_

I think that would be more natural than being in the wiki of the cli implementation of it. Especially now that you have an organization.

Or maybe even make a simple github page for it?

_Copied from original issue: todotxt/todo.txt-cli-fork#16_

**Comment by karbassi** [comment]
@zagortenay333 I agree. Would be nice to have the format in its own repo to discuss patterns and standards.

**Comment by karbassi** [comment]
Done. Moved to [todotxt/todotxt](https://github.com/todotxt/todotxt).

**Comment by zagortenay333** [comment]
Nice.
