### ISSUE TITLE
Configuration file format

### ISSUE THREAD

**Issue by bronzehedwick** [todotxt/todo.txt-cli#226]
I've been searching the documentation for how/what to put in the `~/.todo/config` file - presumably a path to my todo.txt files - but cannot seem to find the expected format.

Thanks.

**Comment by inkarkat** [comment]
The default configuration that ships with todo.txt (see [here](https://github.com/todotxt/todo.txt-cli/blob/master/todo.cfg)) already contains all possible customizations in commented-out form. The syntax itself is that of the _Bash shell_ (in which the CLI is implemented); basically `export CONFIGNAME="value"`, but you can do all sorts of fancy stuff (like conditional config) in there, too.

The path to your todo files can be configured in `TODO_DIR`, or explicitly for each file in `TODO_FILE`, `DONE_FILE`, etc.

**Comment by bronzehedwick** [comment]
Perfect, thanks!
