### ISSUE TITLE
Failure to Sync (Android)

### ISSUE THREAD

**Issue by wenzday** [todotxt/todo.txt-cli#229]
Hi, I'd like to report what seems to be a new bug.  I'm on a Samsund Galaxy 5 with Android 
I"ve been using this app for years and I love it.  
It has always been working great on this phone and on my previous phones.
But in the past week or so, I haven't been able to sync with dropbox. Error message: "Synchronizing Failed" when I open the app or when I try to add a new task or when I click "Sync now"
I confirmed that the file is still in its location on Dropbox. I've tried logging the app out of Dropbox and logging back in. I tried uninstalling the app and reinstalling. 
When I go to "file location" in the settings, it says "Failed to load folder list from Dropbox"
Perhaps this is something that changed with how Dropbox allows other apps to connect to it? I will look into any settings on the Dropbox end and see if I can find any clues there. 
I was wondering if anyone else is having this problem (and if this app is still being updated).
any feedback appreciated!
-wenzday

**Comment by craigmaloney** [comment]
Believe this is related to the bump in Dropbox's API from v1 to v2. Noticed someone mention that Dropbox turned off the v1 API over the weekend.

**Comment by wenzday** [comment]
Alas has the future caught up with this app?

**Comment by Liro67** [comment]
Same issue happens with the IPhone app!
Any plans to upgrade the Dropbox sync feature?

**Comment by karbassi** [comment]
This issue was moved to todotxt/todo.txt-android#483

**Comment by talgalili** [comment]
I'm having a similar issue on my iPhone app. Might this be related?

**Comment by karbassi** [comment]
Duplicate of todotxt/todo.txt-ios#256 and todotxt/todo.txt-android#483
