### ISSUE TITLE
All todo.txt files get empty when synced with other devices

### ISSUE THREAD

**Issue by jerome-tgl** [todotxt/todo.txt-cli#241]
**Do you want to request a *feature* or report a *bug*?**
Bug or question

**What is the current behavior?**
I'm syncing the /Todo folder (where todo.txt, done.txt and report.txt are located) between an Android device and a Macbook Pro with [Syncthing](https://syncthing.net/).
Every time the folder is synced, the content of the files are emptied. I can't even view and restore past versions of these files with the native Mac OS "browse" feature.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. set ```export TODO_DIR="/Users/jerome/Sync/Todo"``, ```export TODO_FILE="$TODO_DIR/todo.txt"``` (idem for others) in .config.
2. sync the folder with [Syncthing](https://syncthing.net/)

**What is the expected behavior?**
The files to get correctly sync without being emptied.
**Which versions todo.sh are you using?**
TODO.TXT Command Line Interface v2.10

**Which Operating System are you using?**
Mac OS High Sierra 10.13.1 (17B1003)

**Which version of bash are you using?**
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)

**Comment by TiZ-HugLife** [comment]
That's very likely going to be a problem with Syncthing, not with todo.txt. todo.txt is just a script that views and manipulates the output of regular text files in a certain structured way. If something is emptying your files, it's a problem with either the android app or with Syncthing.
