### ISSUE TITLE
Linux: command line editor does not understand cursor keys

### ISSUE THREAD

**Issue by prof7bit** [todotxt/todo.txt-cli#244]
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
t replace 1<enter>
Replacement: foo^[[D^[[D^[[D  
It is impossible to move the cursor in the line, instead it just appends more ^[[D at the end

**What is the expected behavior?**
Cursor keys should work to make editing less painful

**Which versions todo.sh are you using?**
TODO.TXT Command Line Interface v2.10

**Which Operating System are you using?**
Kubuntu 17.10

**Which version of bash are you using?**
GNU bash, Version 4.4.12(1)-release (x86_64-pc-linux-gnu)

**Comment by guifeliper** [comment]
@prof7bit The correction was already done if you check the actual version of the repository, it just needs a new release. 
The param `-e` was added on read command and it permits navigates by key arrows. 
 ` read -e input`

**Comment by karbassi** [comment]
Fixed in [v2.11.0](https://github.com/todotxt/todo.txt-cli/releases/tag/v2.11.0)
