### ISSUE TITLE
Add "edit" action

### ISSUE THREAD

**Issue by kjozic** [todotxt/todo.txt-cli#263]
Is it possible to add a new action for editing lines directly in a text editor?
For example `t edit 76` should open line 76 in a text editor.

Here is the script which simulates desired behavior:
```bash
/bin/bash

source ~/.todo/config

if [ -z "$1" ]; then
    echo "Missing line number parameter"
    exit 1
fi

if ! [[ $1 =~ ^[0-9]+$ ]]; then
    echo "Parameter is not number"
    exit 1
fi

NUM_LINES=$(wc -l "$TODO_FILE" | cut -d " " -f 1)

if [ $1 -lt 1 ] || [[ $1 -gt $NUM_LINES ]]; then
    echo "Line number not withing file range"
    exit 1
fi

vim -c ":set nu" -c "startinsert" +$1 "$TODO_FILE"
```

**Comment by iamleot** [comment]
Hello Krešimir,

Krešimir Jozić writes:
> Is it possible to add a new action for editing lines directly in a text editor?
> For example `t edit 76` should open line 76 in a text editor.
> [...]

I think that the `tedit' action listed in:

 <https://github.com/todotxt/todo.txt-cli/wiki/Todo.sh-Add-on-Directory>

does that.

**Comment by kjozic** [comment]
Here is listing of my `t -h`:
```  
Usage: t [-fhpantvV] [-d todo_config] action [task_number] [task_description]

  Actions:
    add|a "THING I NEED TO DO +project @context"
    addm "THINGS I NEED TO DO
          MORE THINGS I NEED TO DO"
    addto DEST "TEXT TO ADD"
    append|app ITEM# "TEXT TO APPEND"
    archive
    command [ACTIONS]
    deduplicate
    del|rm ITEM# [TERM]
    depri|dp ITEM#[, ITEM#, ITEM#, ...]
    do ITEM#[, ITEM#, ITEM#, ...]
    help [ACTION...]
    list|ls [TERM...]
    listall|lsa [TERM...]
    listaddons
    listcon|lsc [TERM...]
    listfile|lf [SRC [TERM...]]
    listpri|lsp [PRIORITIES] [TERM...]
    listproj|lsprj [TERM...]
    move|mv ITEM# DEST [SRC]
    prepend|prep ITEM# "TEXT TO PREPEND"
    pri|p ITEM# PRIORITY
    replace ITEM# "UPDATED TODO"
    report
    shorthelp

  Actions can be added and overridden using scripts in the actions
  directory.

  See "help" for more details.
```

I don't see the `edit` action. 

Maybe I expressed myself wrong - I would like to see `edit specific line` action. That means that I would like to open todo.txt at a specific line, not just to open it in an editor at the beginning.

**Comment by inkarkat** [comment]
I have an `todo.sh edit` add-on action, too: https://github.com/inkarkat/todo.txt-cli-ex/blob/master/actions/edit

    edit [ITEM#] [SRC]
      Open ITEM# in $TODO_DIR/SRC in $EDITOR for editing.
      If ITEM# is omitted, the entire file is edited.
      If SRC is not given, defaults to 'todo'.
      ITEM# can be removed by deleting the line.
      Additional tasks can be added by appending more lines.

It uses the `$EDITOR` environment variable instead of hard-coding Vim. It's based on [Matt Brubeck's add-on action](https://github.com/mbrubeck/todo.txt-cli/blob/master/todo.actions.d/edit). As you can see, there are many implementations to choose from :-) I don't think we should include this in the main script; this is a perfect use case for add-ons.

**Comment by kjozic** [comment]
Thanks. That action will be acceptable.
