### ISSUE TITLE
Bad directory

### ISSUE THREAD

**Issue by marie-bnl** [todotxt/todo.txt-cli#265]
**Do you want to request a *feature* or report a *bug*?**

I want to report a **bug**

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/39555268/48678278-73265280-eb81-11e8-9f17-859c2d54ef9c.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Use the Manjaro Linux distribution, do `yay todotxt`, install the version from git or not then try to add a task or list them.

**What is the expected behavior?**

The first command adds the task and the second one lists the tasks

**Which versions todo.sh are you using?**

TODO.TXT Command Line Interface v2.11.0

**Which Operating System are you using?**

Manjaro Linux 18 Illyria
![image](https://user-images.githubusercontent.com/39555268/48678307-d6b08000-eb81-11e8-9e7e-d3b822171830.png)

**Which version of bash are you using?**
I use ZSH. <br>
zsh 5.6.2 (x86_64-pc-linux-gnu)

I tried to reproduce this bug with bash and the bug also appears

**Comment by malockin** [comment]
*Edit: sorry, I just noticed that you use **ZSH** and not **bash**. I'm not really familiar with **ZSH**, but the general idea still applies - you need to point **todo.sh** to a configuration file that configures **TODO_DIR** to a writable location.*

The script tries to find the **todo.txt** file under its current path, but that path is not writable by a normal user. You'll need to provide it with a path to the file you want to use, which is done through the configuration file.

For example, on my machine, I have a **todo** folder under my home folder, and I've aliased **todo.sh** to always use it by setting it up in the configuration file, and pointing **todo.sh** to use that file.

Create a **todo** folder under your home folder:
```bash
mkdir ~/todo
```

Then copy the default configuration file to it:
```bash
cp /usr/share/todotxt/todo.cfg ~/bin
```
*Note: I assume this is where the Manjaro package placed the configuration file. If it's not there, you may need to search for it.*

After that, edit the configuration file, and make sure that the **TODO_DIR** variable points to your own **todo folder**:
```bash
export TODO_DIR=$HOME/todo
```

And finally, add the following alias to you `.bashrc` file:
```bash
alias t='/usr/bin/todo.sh -d ~/todo/todo.cfg'
```

After you log in again (or `source` your `.bashrc` file), you should be able to use it.

**Comment by marie-bnl** [comment]
I have not seen the answer and I now use another tasks manager. But this solution seems perfect, and should work. I close this issue
