### ISSUE TITLE
Not working in Ubuntu 19.04

### ISSUE THREAD

**Issue by jsf15** [todotxt/todo.txt-cli#280]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**
Doesn't run

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
After updating to Ubuntu 19.10 the extension gives error at Gnome Shell Extension site and won't run

**What is the expected behavior?**
To work as in version 18.10

**Which versions todo.sh are you using?**
> Run `todo.sh -V`
Latest

**Which Operating System are you using?**
Ubuntu 19.04

**Which version of bash are you using?**
> Run `bash --version`
5.0.3

**Comment by jueqingsizhe66** [comment]
Works in Ubuntu 19.04

```
export PATH=$PATH:"~/TodoXshell/todo.txt_cli-2.9"
alias t='todo.sh -d ~/TodoXshell/todo.txt_cli-2.9/todo.cfg'
export TODOTXT_DEFAULT_ACTION=ls
source ~/TodoXshell/todo.txt_cli-2.9/todo_completion
complete -F _todo t

alias cdtodo="cd ~/TodoXshell/todo.txt_cli-2.9"
```

**Comment by jueqingsizhe66** [comment]
chmod todo.sh to be executable

**Comment by edi9999** [comment]
This question can be closed imo
