### ISSUE TITLE
Prioritize multiple tasks in one command

### ISSUE THREAD

**Issue by edi9999** [todotxt/todo.txt-cli#281]
**Do you want to request a *feature* or report a *bug*?**

A feature

**What is the current behavior?**

to pri takes only one task as an argument

**What is the expected behavior?**

I would like to prioritize multiple tasks in one command, for example `to pri 1,2,3 C`

I'm not really attached to a given syntax, it could also be like in `to do` where we can do `to do 1 2 3`, then we could to the same for to pri with `to pri 1 2 3 C`

**Which versions todo.sh are you using?**
> Run `todo.sh -V`

TODO.TXT Command Line Interface v2.11.0

**Which Operating System are you using?**

Ubuntu 18.04

**Which version of bash are you using?**
> Run `bash --version`

GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)

**Comment by pmust** [comment]
It would be nice to have this as default. This is also how it works with `rm`. You can fix it yourself by making a new command `pri` under `.todo.actions.d` with contents from here: https://pastebin.com/PQL79KMM (I modified my `rm` command for `pri`). Then you can use `... pri pri_arg task1 task2 task 3...` as command, for instance I would use `t pri A 12 13 14 15` as my `todo.sh` is aliased to `t`.
