### ISSUE TITLE
Add descriptions to tasks

### ISSUE THREAD

**Issue by Numilani** [todotxt/todo.txt-cli#282]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
Tasks only accept a task description

**What is the expected behavior?**
Tasks could have a description added to them using, for example, `t desc <description>`

**Which versions todo.sh are you using?**
2.11.0

**Which Operating System are you using?**
Ubuntu 18.04.2

**Which version of bash are you using?**
4.4.19

**Comment by DoctorSubtilis** [comment]
+1

**Comment by inkarkat** [comment]
Not sure what's the difference between the existing task subject and description... just longer text (including newlines)?
Any such extension would require a syntax extension (in https://github.com/todotxt/todo.txt) first. Also, there are custom add-ons that add (external) notes already.
