### ISSUE TITLE
Guidance needed to fix error code 1 on test 3 of t6080

### ISSUE THREAD

**Issue by bengineerdavis** [todotxt/todo.txt-cli#285]
**Do you want to request a *feature* or report a *bug*?**
No.

**What is the current behavior?**
I successfully run `make`, and `make install`, but on running 'make test' I get the following message:
`*   ok 1: todo2.sh executable
*   ok 2: all todo2 contexts
* FAIL 3: todo2.sh executable not in PATH
todo2.sh 
expected exit code 127, actual 1
*   ok 4: all todo2 contexts
* failed 1 among 4 test(s)
make: *** [Makefile:81: tests/t6080-completion-path.sh] Error 1
`
I'm using the default settings for the location of todo.sh.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
My install should pass the tests.

**Which versions todo.sh are you using?**
> Run `todo.sh -V`

> TODO.TXT Command Line Interface v2.11.0.dirty

**Which Operating System are you using?**
Fedora 30

**Which version of bash are you using?**
> Run `bash --version`

> GNU bash, version 5.0.7(1)-release (x86_64-redhat-linux-gnu)

**Comment by karbassi** [comment]
@bengineerdavis was this fixed? Can you report back?

**Comment by bengineerdavis** [comment]
I ended up using [Topydo](https://github.com/topydo/topydo), if I remember the original reason I started using this. I'm on a much newer OS (Ubuntu 20 LTS)--since Fedora 30 hasn't been supported for awhile now. I could try and reproduce on that system, if that's useful.

**Comment by karbassi** [comment]
Thanks for reporting back. No need to replicate this bug since, as you said, Fedora 30 isn't supported.

Closing this. 👍🏽
