### ISSUE TITLE
Todo.txt CLI should look for current directory `todo.txt` file or config first

### ISSUE THREAD

**Issue by eightyfive** [todotxt/todo.txt-cli#288]
**Do you want to request a *feature* or report a *bug*?**

FEATURE

**What is the current behavior?**

Only add todos to a single centralized `todo.txt` file.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Not a bug.

**What is the expected behavior?**

- The CLI tool should look in the current folder (`pwd`) for a `todo.txt` file and add to it if found.
- Alternatively it should look for some standardized `todo.config` file name in current directory
- It should fallback to "normal" centralized `todo.txt` file if not found
- It should output some kind of message alerting which file has been updated
- This would remove the need to type the `-d` config option all the time `t -d ./todo.config add "buy the milk"`
- In case of not config in current dir, it would simply add to local, current `todo.txt`, removing the need to create a local `todo.txt` config file

**Which versions todo.sh are you using?**

```
TODO.TXT Command Line Interface v2.11.0
```

**Which Operating System are you using?**

macOS

**Which version of bash are you using?**

```
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

**Comment by eightyfive** [comment]
Allo?

**Comment by inkarkat** [comment]
What's the use case for having many distributed todo files? To me, that's rather an anti-pattern, as `todo.txt` has all the filtering (by project, context) to manage any tasks in a central place. There have been requests to separate work and private tasks, and that usually is achieved by having two different config files (which allow other differentiations as well), and aliases to automatically choose one or the other.

If you really want that, it should be enough to `export TODO_DIR=.` in the configuration, shouldn't it?! The config file is sourced, so you can even put logic inside (like a test and fallback to a global `todo.txt` if no local one exists - though I personally would never want such behavior).

**Comment by eightyfive** [comment]
Hi!

- My use case is basically having one `todo.txt` per (code) repository.
- In order to use `todo.txt-cli` as a DEV tool, managing my `todo.txt` todos on a per repo basis.
- And without having to specify the (local) config file (`-d` option) every time.

Does it make sense?

Thanks!

**EDIT**
So I can commit the `todo.txt` file per repo...

**Comment by inkarkat** [comment]
Okay, having the tasks committed (and potentially shared this way among team members) may make sense. Still, I don't think that we need a modification of todo.txt itself; you can check for such local todo file in the config file, and then set `TODO_DIR` accordingly. If you use something like `git rev-parse --show-toplevel` (for Git), this would even work from subdirectories of the repository, and you could make the logic look into `<repo root>/tasks/todo.txt` instead; something that the suggested general lookup in the current directory could never achieve.

**Comment by eightyfive** [comment]
> If you really want that, it should be enough to export TODO_DIR=. in the configuration, shouldn't it?!

That works for me! This is what I need. NOT using a default central configuration/todo file, this works like a charm.

**Comment by eightyfive** [comment]
FYI

Here is my `$HOME/.todo.cfg` file so it does not create rogue `todo.txt` files everywhere 😄:
```sh
export TODO_DIR=.

# ... TODO_FILE, etc...

if [ ! -e $TODO_FILE ]; then
    echo "Error: No todo.txt file found"
    exit 1
fi

# ...
```

**Comment by zachcran** [comment]
Five years later, but I found this issue and the solution informative for the exact same workflow described here (separate todo files per code repository or shared project). I wanted to share my solution to this, too, in case it is useful to anyone else. I hope this is okay!

## Description

I loosely based the behavior on how `nb` handles [global vs. local notebooks](https://xwmx.github.io/nb/#global-and-local-notebooks). The solution below uses a "global" todo directory with my main todo files unless the current directory contains `todo.txt`. Then it defaults to the local `todo.txt` with the option to override TODO_DIR, TODO_FILE, DONE_FILE, and/or REPORT_FILE by setting them in your environment for an alternative location or to point back to the global location when needed.

I like the idea that I've seen suggested in other issues of using aliases+different config files to manage multiple todo directories, too, but haven't had a need for it yet. I could see combining aliases with this "local todo" method to make a `todo-global` or `tg` alias that always accesses the global todo files, or, conversely, `todo-local` or `tl` aliases to explicitly use local todos.

## Code

```bash
# ... Near top of todo config, replacing default location-setting code ...

# Global todo directory, regardless of whether using local todo files
global_todo_dir=${XDG_DATA_HOME:-$HOME/.local/share}/todo

# Base filenames
todo_file="todo.txt"
done_file="done.txt"
report_file="report.txt"

# Determines todo.txt directory to use.
# This checks for a local todo file and, if one exists, uses the current
# directory as the todo directory. Otherwise, it uses the global todo directory.
if [[ -f "$PWD/$todo_file" ]]; then
    export TODO_DIR="${TODO_DIR:-$PWD}"
else
    export TODO_DIR="${TODO_DIR:-$global_todo_dir}"
fi

# todo/done/report.txt locations
export TODO_FILE="${TODO_FILE:-$TODO_DIR/$todo_file}"
export DONE_FILE="${DONE_FILE:-$TODO_DIR/$done_file}"
export REPORT_FILE="${REPORT_FILE:-$TODO_DIR/$report_file}"

# Actions directory location
export TODO_ACTIONS_DIR="$global_todo_dir/todo.actions.d"

# ... Remaining configs (colors, addon options, etc.) ...
```
