### ISSUE TITLE
add command does not check/add preceding newline character

### ISSUE THREAD

**Issue by owenh000** [todotxt/todo.txt-cli#294]
I think this should be considered a **bug** because it can cause data loss/corruption.

**Current behavior:**

The **add** command fails to add a new task entry if the `todo.txt` file does not end in a newline (`\n`). This can happen easily with certain editors (such as Mousepad) that do not automatically add a newline character at the end of a file.

**Steps to reproduce:**

This behavior can be simulated with Nano's `--nonewlines` option, or with `echo -n` like this:

```
$ echo -n "This is a low/no priority task" >| todo.txt
```

At this point, the `todo.txt` file has one task but does *not* have a line break at the end.

Now we can use the **add** command to create a new task:

```
$ todo-txt add "(A) This is a high-priority task"
```

And then list the tasks:

```
$ todo-txt ls
This is a low/no priority task(A) This is a high-priority task
```

The new high-priority task has been "lost" because it was not placed on a line of its own.

**Expected behavior:**

*todo-txt* should check for a newline character (`\n`) at the end of the file and, if it is missing, add it before the new task entry.

**Versions:**

- todo-txt 2.11.0 on Debian GNU/Linux
- bash 5.0.3(1)-release

**Comment by owenh000** [comment]
@inkarkat and @karbassi, thanks for writing and merging a fix for this!

Perhaps this can be included in a new release soon.

**Comment by karbassi** [comment]
@owenh000 I'll probably do a release in April.
