### ISSUE TITLE
Adding option to list items numerically instead of alphabetically

### ISSUE THREAD

**Issue by aimforthebushes** [todotxt/todo.txt-cli#303]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
List items alphabetically

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions todo.sh are you using?**
TODO.TXT Command Line Interface v2.11.0

Homepage: http://todotxt.org
Code repository: https://github.com/todotxt/todo.txt-cli/
Contributors: https://github.com/todotxt/todo.txt-cli/graphs/contributors
License: https://github.com/todotxt/todo.txt-cli/blob/master/LICENSE

**Which Operating System are you using?**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Pop!_OS 19.10"
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

**Which version of bash are you using?**
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by inkarkat** [comment]
That option already exists, in the form of `TODOTXT_SORT_COMMAND`; for example, to sort alphabetically (after the _ITEM#_ and a following _add-date_):

    TODOTXT_SORT_COMMAND='sort -k 3' todo.sh ls

You can make that permanent by `export`ing it in your configuration file.

If you think this is a super important use case that warrants a dedicated command-line option, please elaborate. This is the first time that I've heard of this kind of request, though.

**Comment by aimforthebushes** [comment]
The thing is that I want to split a task in multiple smaller tasks in order to complete it. I have introduced the tasks so I can follow them in order but the script ignores my order.

The problem that I see is that:
1.- The script adds line numbers when there is no line number in todo.txt file (I understand that this is done so you can edit or delete a task using them as reference which is good)
2.- It presents tasks in a different order in which tasks were introduced in todo.txt file.
3.- It's less intuitive, since numbers have been used forever to express order and continuity, therefore it makes more complicate to complete tasks in certain order.

**Comment by inkarkat** [comment]
As I wrote, you're free to adapt the sorting to your needs (via `TODOTXT_SORT_COMMAND`).

I understand the need to establish a task order, but your scheme would need some sort of grouping, else how would you distinguish between a task group to be done in order, and just unrelated tasks added one after another?

_Priorities_ could be used for that ordering; i.e. tasks to be done first are prioritized `(A)`, next ones `(B)`, and so on.

I personally try to avoid task dependencies if at all possible (for maximum flexibility in doing them); if there really are hard non-obvious dependencies, I've invented a special `w:<NUMBER>` (_waiting for task NUMBER_) scheme, but the implementation is anything but simple; adapting the sort order is much easier.

**Comment by aimforthebushes** [comment]
> I understand the need to establish a task order, but your scheme would need some sort of grouping, 

Yeah. That's what Projects are for.

I've tried `TODOTXT_SORT_COMMAND='sort -k 3' todo.sh ls` and it didn't work but after tinkering a little bit I've found out that `TODOTXT_SORT_COMMAND='sort -k 1' todo.sh ls` does the trick.

Thank you.
