### ISSUE TITLE
No color display

### ISSUE THREAD

**Issue by aimforthebushes** [todotxt/todo.txt-cli#304]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
It does not display colors

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
todo-txt ls

**What is the expected behavior?**

**Which versions todo.sh are you using?
TODO.TXT Command Line Interface v2.11.0

Homepage: http://todotxt.org
Code repository: https://github.com/todotxt/todo.txt-cli/
Contributors: https://github.com/todotxt/todo.txt-cli/graphs/contributors
License: https://github.com/todotxt/todo.txt-cli/blob/master/LICENSE

**Which Operating System are you using?
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Pop!_OS 19.10"
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

**Which version of bash are you using?
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by inkarkat** [comment]
More information is needed to help you. What terminal do you use, what's the value of `$TERM`?

Do other commands (`ls --color=auto`) show colors? Do you see colors with `echo -e 'this is \e[01;33;41mRED\e[0m'`?

The interface to show colors in the terminal is very simple; it's very unlikely that there's a bug in todo.sh; rather, this is a misconfiguration of some kind.

**Comment by aimforthebushes** [comment]
1.- I am using Gnome Terminal
2.- TERM = xterm-256color
3.- Yes. The command `echo -e 'this is \e[01;33;41mRED\e[0m'` shows color.
4.- I am using Powerline (not sure if this helps)

**Comment by inkarkat** [comment]
So your terminal is capable of showing colors; this means that it's a misconfiguration of `todo.sh`. Please check that `-p` (plain) isn't passed, and that the `TODOTXT_PLAIN` environment variable is either unset or not `1`. It's less likely that a filter removes the color sequences from the output; `-x` would disable that.

It's likely that the answer is in your `todo.cfg` configuration file; you could try to temporarily rename it; the colors should then reappear.

**Comment by karbassi** [comment]
Closing since it seems to be answered and stale.
