### ISSUE TITLE
How to delete completed tasks?

### ISSUE THREAD

**Issue by ShaneTian** [todotxt/todo.txt-cli#305]
When I use `todo.sh lsa`, the screen always displays `DONE: 0 of 3 tasks shown`. Is there any command to clear the completed work?

**Which versions todo.sh are you using?**
> TODO.TXT Command Line Interface v2.11.0

**Which Operating System are you using?**
> macOS Catalina 10.15.4

**Which version of bash are you using?**
> zsh 5.7.1 (x86_64-apple-darwin19.0)

**Comment by inkarkat** [comment]
`done.txt` is meant to be the long-term archive of tasks that have been done. If you don't need them any longer, just backup / delete that file; it will be re-created on the next `todo.sh archive` run.

	$ rm ~/todo/done.txt
