### ISSUE TITLE
Error 404 on CONTRIBUTING.md

### ISSUE THREAD

**Issue by luilver** [todotxt/todo.txt-cli#306]
When I click on [_contributing guide_](https://github.com/todotxt/todo.txt-cli/blob/master/CONTRIBUTING.md) I'm getting **404 Not found**

**Comment by inkarkat** [comment]
Please check out the latest version (by updating your `master` branch, or here on GitHub). The current location is https://github.com/todotxt/todo.txt-cli/blob/master/.github/CONTRIBUTING.md (the file moved to a `.github` subdirectory), and as far as I can tell, the links have been properly adapted.

**Comment by inkarkat** [comment]
Oh, I missed that there are two links; the first one indeed is wrong.

**Comment by luilver** [comment]
You bet !
