### ISSUE TITLE
Fatal Error: Cannot read configuration file /Users/{name}/.todo/config

### ISSUE THREAD

**Issue by mhomol** [todotxt/todo.txt-cli#315]
**Bug but probably User Error lol**
I just installed via homebrew and tried to add my first item and got hit with this:
Fatal Error: Cannot read configuration file /Users/{myname}/.todo/config
I checked that indeed that folder doesn't exist. Is this a `chmod` scenario?

**What is the expected behavior?**
That an item adds :)

**Which versions todo.sh are you using?**
v2.11.0

**Which Operating System are you using?**
MacOS

**Which version of zsh are you using?**
zsh 5.7.1 (x86_64-apple-darwin19.0)

**Comment by karbassi** [comment]
Duplicates #252
