### ISSUE TITLE
Replace yahoo group

### ISSUE THREAD

**Issue by cunla** [todotxt/todo.txt-cli#325]
Yahoo groups is closing on Dec 15, 2020.
Migrate to google groups?

**Comment by karbassi** [comment]
Moving to Github Discussions. https://github.com/todotxt/todo.txt-cli/discussions

Thanks for bringing this up @cunla

**Comment by cunla** [comment]
Update wiki pages? https://github.com/todotxt/todo.txt-cli/wiki/Quick-Start-Guide
