### ISSUE TITLE
Add subtask functionality

### ISSUE THREAD

**Issue by team-community** [todotxt/todo.txt-cli#390]
Hi all. Many tasks are very complex or time-consuming. It makes sense to add subtask functionality. The user can break the task into small tasks and solve them over time. In the end, he will solve the main problem. It would be very helpful. For example, for tasks like learning languages.

**Comment by inkarkat** [comment]
Hi Aysun, thanks for the suggestion.

The todo.sh functionality only covers the core of task tracking, as everyone's processes and requirements are different. The program can be extended easily via _add-ons_; many users have already experimented with subtasks / dependencies among tasks. With that in mind, I'm afraid that subtasks will likely never be added to the core program itself.

---

My personal take on that topic is a set of add-on commands around inter-task dependencies; you'll see these illustrated in this [test for depview](https://github.com/inkarkat/todo.txt-cli-ex/blob/master/tests/t2050-depview.sh), but there are several more custom commands involved (e.g. `wait`, `unwait`, `lswait`).

A more lightweight alternative is the ability to do parts of a task via my [dopart add-on](https://github.com/inkarkat/todo.txt-cli-ex/blob/master/actions/dopart); again, [this test](https://github.com/inkarkat/todo.txt-cli-ex/blob/master/tests/t2400-dopart.sh) illustrates its use. That one just needs the [lib/common.sh](https://github.com/inkarkat/todo.txt-cli-ex/blob/master/lib/common.sh) helper script, so you might be able to lift this from my personal customization and use it for yourself. (Though I generally have published my extensions only as an inspiration - they're too intertwined and complex for direct use by others, unfortunately.)
