### ISSUE TITLE
Feature Wanted: colorized style continues to the end of the line

### ISSUE THREAD

**Issue by rustle123** [todotxt/todo.txt-cli#397]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
plz see the screenshot as below: 
<img width="1265" alt="Snipaste_2022-11-29_21-32-29" src="https://user-images.githubusercontent.com/63949101/204543759-37a354d8-49a4-425e-bc99-a79330bd9378.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. add some todos using `tt add ...`
2. set pri to some of them
3. executing `tt ls` will see the priority ones will be colorized, but not to the end of their line correspondingly

**What is the expected behavior?**
I hope the priority lines would be colorized to then end of its line. 
AND I tried to modify the source code and find the code as below, but failed, so could you help to add this feature to this useful tool?
![image](https://user-images.githubusercontent.com/63949101/204545435-d15d8cbe-fd71-460e-aad6-f991a287831c.png)

**Which versions todo.sh are you using?**
> Run `todo.sh -V`
TODO.TXT Command Line Interface v2.12.0

**Which Operating System are you using?**
Debian 11.5

**Which version of bash are you using?**
> Run `bash --version`
GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)

**Comment by inkarkat** [comment]
I think the only way this can be done is through adding spaces at the end of each task to fill up the terminal width. As long as you can assume that each character is one screen cell wide this is easy, but hard considering double-width characters, tabs, emojis.

You seem to be using an unorthodox format with a custom timestamp, and |-aligned columns for projects and scheduling. If you have that formatting inside the todo file itself, that would go aginst the simplicity spirit of todo.txt; but if you use a custom filter to add the formatting to the tasks, you could easily implement the full line coloring there (and it would have to be less generic as you know what kind of characters you personally use).

**Comment by rustle123** [comment]
`tt a "@${tdate --date='string'} | +project | T:TBD | something to do......."` 

alias tdate='date +%Y-%m-%dT%H:%M:%S'

yes, I use a python script & inotify tools to process todo.txt. Whenever the file is opened or modified, the python script will be executed, and `tt ls`will supply a pretty format. I think it's better to be done by shell scripts.

OK, I will try to impement this using python scripts, thx anyway.
