### ISSUE TITLE
Support urgency and/or due date in core format

### ISSUE THREAD

**Issue by githorse** [todotxt/todo.txt-cli#409]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

New to todo.sh, but right out of the gate I'm stumbling over the lack of some concept of urgency in addition to priority. There are always going to be low-importance but (relatively) high urgency tasks ("take out the garbage") in addition to high-importance but low-urgency tasks ("get a better job") -- along the lines of [the Eisenhower matrix](https://asana.com/resources/eisenhower-matrix). To me it seems like "priority" is really a one-dimensional projection of the two dimensions of urgency and importance, but I need my system to handle both. 

What are people's thoughts on this?

**Comment by inkarkat** [comment]
Note: Any extension to the todo.txt format would need to be directed at https://github.com/todotxt/todo.txt - this is just the Bash command-line client implementation, and any extension should be rolled out across all existing clients eventually.

---

Personally, I don't see this need, or rather to me it's implicitly included already: Urgent tasks are at the bottom (active) end of the list. If they're not actually that urgent or important, they'll bubble down the list over time - those old tasks at the top (old) end of the list are all quadrant IV ones: not urgent and not important (and can be pruned).

I had tracked the quadrant distribution of my tasks over several years - it's an interesting exercise to see how many urgent interruptions there are, and what percentage is made up of the "high quality" quadrant II stuff. However, I did this retroactively, in the calendar where I recorded my working hours. I did not feel the need to introduce this information to my future-directed task tracking system.

**Comment by githorse** [comment]
Thanks @inkarkat -- I'll check that repo and maybe post the question there if it's not there already. But I'm a little confused at your answer:

> Urgent tasks are at the bottom (active) end of the list. If they're not actually that urgent or important, they'll bubble down the list over time.

By "urgent" here do you mean "priority A"? O something else? If it's priority `A`, how does it bubble down (up?) the list? As I say I'm new here so I might be missing something about how the system works.

**Comment by inkarkat** [comment]
By "urgent" I mean that it has to be done soon, i.e. today or at least within the next couple of days. I typically enter and do about a handful of tasks each day, so the urgent ones will be at the bottom, whereas the influx of tasks will mean that the non-urgent ones move up. That's what I meant - the urgency is somewhat implicitly encoded in the position of the task relative to the end.

For true importance, that's what the A-Z priority is for; there might be an important task, but if it's not urgent I'll move up in the list soon, and the explicit priority assignment helps in locating it over the other unprioritized tasks.
