### ISSUE TITLE
Document how to add due dates

### ISSUE THREAD

**Issue by githorse** [todotxt/todo.txt-cli#410]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

It sounds like [it's possible to handle due dates in some way outside the core format](https://github.com/todotxt/todo.txt-cli/issues/286), but I don't understand how. Could the docs be updated to mention that? Surely many people would like to know how to use that feature.

See [related issue on urgency](https://github.com/todotxt/todo.txt-cli/issues/409).

**Comment by inkarkat** [comment]
The _schedule_ add-on is listed on the [add-on directory Wiki page](https://github.com/todotxt/todo.txt-cli/wiki/Todo.sh-Add-on-Directory#schedule-work-with-date-threshold). As long as it's not part of todo.txt-cli itself, it would be confusing to mention this more prominently.

Some users are content with the basic out-of-the-box functionality, other more aspiring users will surely find that directory (it's frequently linked to in the discussions or earlier on the now defunct mailing list) and go through it.
