### ISSUE TITLE
[question] is there a way to undo a task?

### ISSUE THREAD

**Issue by mb6ockatf** [todotxt/todo.txt-cli#433]
...except manually editing files in `~/.todo`?
by the way, nowhere in the repository (or i wasn't attentive, sorry in this case) it is mentioned that things are stored in `~/.todo`. had to lookup into source code to find out. may be mention it in the readme file?

```
$ todo.sh -V
TODO.TXT Command Line Interface v@DEV_VERSION@
```
archlinux 6.6.25-1-lts

```
$ bash --version
GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu)
```

**Comment by pabgan** [comment]
https://github.com/pabgan/undo

That's the one I created. But you can't use autoarchive `-A`, it will only undo tasks that still are in `todo.txt` not those in `done.txt.
