### ISSUE TITLE
Allow to select task via fuzzyfind (fzf)

### ISSUE THREAD

**Issue by thrien** [todotxt/todo.txt-cli#437]
## Feature Request

Allow to select a task by content instead of linenumber, e.g. via a fuzzyfinder. In all cases where a mandatory task is not provided it is chosen interactively.

## Example

I've used [fzf](https://junegunn.github.io/fzf/) as a convenient fuzzyfinder on the commandline to show how this could work:

![todo_fzf](https://github.com/todotxt/todo.txt-cli/assets/39382079/9e4acdd1-8257-4b4d-9302-a31f54fa39b4)

If you don't specify a linenumber you get an interactive prompt to select one.

For this simple preview I changed line [1224](https://github.com/todotxt/todo.txt-cli/blob/fd753c6c2e8e661d9882eb41af4ec3a2429b6484/todo.sh#L1224) to:
```
    [ "$#" -eq 0 ] && set -- "$(_list "$TODO_FILE" | fzf --height=~10 | awk '{ print $1 }')"
```

## Implementation

I need some guidance by someone more familiar with the code to come up with a proper implementation.

- What's the cleanest way to get all the tasks/lines with linenumber prefixed but without prompt, etc. ?
- It probably makes sense to write a function for this.
    * Does it to respect anything else apart from TODO_FILE?
- Since this feature will add a new dependency it would need to be checked beforehand.
    * Where is the best place to do this?
    * Should there be an option to allow/force/deactivate this feature?
    * How to check if terminal is interactive? (that's something I can probably figure out myself)

**Comment by pabgan** [comment]
You can do it with an alias:
```sh
todo.sh do $(todo.sh ls | head -n-2 | fzf --ansi | cut -d' ' -f1)
```
I think maintainers wants to keep main script as simple as possible.

**Comment by thrien** [comment]
Okay, fair enough. Maybe that's a feature for one of the many apps built on top of it.

Then let me just mention for future reference how to use [dmenu](https://tools.suckless.org/dmenu) in this case. With these two patches

- [fuzzymatch](https://tools.suckless.org/dmenu/patches/fuzzymatch)
- [printindex](https://tools.suckless.org/dmenu/patches/printindex)

it can be nicely integrated as follows

``` sh
dmenu -w "$WINDOWID" -F -ix -p "Select a task:" < "$TODO_FILE" | xargs expr 1 +
```
