### ISSUE TITLE
`make uninstall` fails because it tries to `rmdir` non-empty `bash_completion.d`

### ISSUE THREAD

**Issue by ss-raicangu** [todotxt/todo.txt-cli#451]
**Do you want to request a *feature* or report a *bug*?**

Bug report

**What is the current behavior?**

~~~sh
sudo make uninstall
~~~

_Ref 1. Running the above..._

~~~
rm -f /usr/local/bin/todo.sh
rm -f /usr/local/share/bash_completion.d/todo
rm -f /usr/local/etc/todo/config
rmdir /usr/local/share/bash_completion.d
rmdir: failed to remove '/usr/local/share/bash_completion.d': Directory not empty
make: *** [Makefile:108: uninstall] Error 1
~~~

_Ref 2. ... results in this error._

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Please see above.

**What is the expected behavior?**

~~~diff
diff --git a/Makefile b/Makefile
index e17e773..b9c6e0a 100644
--- a/Makefile
+++ b/Makefile
@@ -106,7 +106,7 @@ uninstall:   ## uninstall package
        rm -f $(DESTDIR)$(datarootdir)/todo
        rm -f $(DESTDIR)$(sysconfdir)/todo/config
 
-       rmdir $(DESTDIR)$(datarootdir)
+       rm -f $(DESTDIR)$(datarootdir)/todo.sh
        rmdir $(DESTDIR)$(sysconfdir)/todo
 
 # create local installation directories
~~~

_Ref 3. Possibly should be deleting the `todo.sh` completion file only, instead of attempting to delete the `bash_completion.d` directory?_

**Any other issues?**

~~~diff
diff --git a/README.md b/README.md
index 877981e..7afd931 100644
--- a/README.md
+++ b/README.md
@@ -41,9 +41,9 @@ make test
 
 *NOTE:* Makefile defaults to several default paths for installed files. Adjust to your system:
 
-- `INSTALL_DIR`: PATH for executables (default /usr/local/bin)
+- `INSTALL_DIR`: PATH for executables (default `/usr/local/bin`)
 - `CONFIG_DIR`: PATH for the todo.txt configuration template
-- `BASH_COMPLETION`: PATH for autocompletion scripts (default to /etc/bash_completion.d)
+- `BASH_COMPLETION`: PATH for autocompletion scripts (default to `/usr/local/share/bash_completion.d`)
 
 ```shell
 make install CONFIG_DIR=/etc INSTALL_DIR=/usr/bin BASH_COMPLETION=/usr/share/bash-completion/completions
~~~

_Ref 4. On a side note, noticed that the README states that default completion directory is `/etc/bash_completion.d`, when it actually seems to be `/usr/local/share/bash_completion.d`. Should this be updated?_

**Which versions todo.sh are you using?**
> Run `todo.sh -V`

* Built from `v2.13.0-31-g4129dad` but probably not that relevant :slightly_smiling_face: .
* GNU Make 4.3

**Which Operating System are you using?**

Ubuntu 22.04

**Which version of bash are you using?**
> Run `bash --version`

GNU bash 5.1.16

**Comment by ss-raicangu** [comment]
I am happy to create a PR, if desired :slightly_smiling_face: . Thanks in advance for considering this report.

**Comment by inkarkat** [comment]
Thank you for the excellent bug report, and your offer to create a pull request! I didn't take you up on this because I think the actual location (`/usr/local/share/bash_completion.d`) is also wrong; the completion likely didn't work for you at all?!

**Comment by ss-raicangu** [comment]
> the completion likely didn't work for you at all?!

Good point. Didn't even consider this but yea, it did not :sweat_smile: .
