### ISSUE TITLE
Color doesn't get displayed

### ISSUE THREAD

**Issue by apraditya** [todotxt/todo.txt-cli#96]
Hi,

I am having issue with the highlighting. The color doesn't get displayed. I only have `TODO_DIR` modified in the config file. I'm using 2.9 on OS X with iTerm2. I don't think iTerm2 color profile has anything to do with this as I have the same problem in Terminal. It's not my zsh settings (using oh-my-zsh) as well as switching to bash doesn't help. I tried uncommenting the color map setting still doesn't help. 

I searched for the problem on the web or in this issue archive and couldn't find the similar problem. I have no idea what else to check. Appreciate your advise. Thanks!

**Comment by juanibiapina** [comment]
Colors also don't work for me.

**Comment by craigmaloney** [comment]
Hi @juanibiapina,

This is likely a separate issue. Please open a new issue and include information about your system (OS, terminal you're using, etc.).

Thanks!
